// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yfieuexisaacekljaffq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmaWV1ZXhpc2FhY2VrbGphZmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNTAzNDYsImV4cCI6MjEwMTkyNjM0Nn0.JL2VMWjBidD9N8BP4ftFftoq8XannSP-n2aj_3zc8j0";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
